apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chorro
    component: server
  name: chorro-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chorro
      component: server
  template:
    metadata:
      labels:
        app: chorro
        component: server
    spec:
      containers:
        - image: ghcr.io/skeswa/chorro-server:0.0.2
          name: chorro-server
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 128M
