// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// An individual user registered with Chorro.
type User struct {
	// Email address of this User.
	//
	// Can be null if the currently authenticated User does not have access to this
	// information.
	Email *string `json:"email"`
	// First name of this User.
	FirstName string `json:"firstName"`
	// Uniquely identifies this User.
	ID string `json:"id"`
	// First name of this User.
	LastName string `json:"lastName"`
}
