apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chorro
  name: chorro-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chorro
  template:
    metadata:
      labels:
        app: chorro
    spec:
      containers:
        - image: ghcr.io/skeswa/chorro-web:0.1.2
          name: chorro-web
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 256M
