apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chorro
    component: web
  name: chorro-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chorro
      component: web
  template:
    metadata:
      labels:
        app: chorro
        component: web
    spec:
      containers:
        - image: ghcr.io/skeswa/chorro-web:0.2.0
          name: chorro-web
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
